version: 2

sources:
  - name: pjnpoc1
    database: dbtworkshop
    schema: pjnevents
    tables:
      - name: durable_consumerorderactivatedevent
      - name: durable_consumerordermanualpaymentfailedevent
