version: 2

sources:
  - name: pjnpoc1
    database: dbtworkshop
    schema: pjnevents
    tables:
      - name: durable_consumerorderactivatedevent
      - name: durable_consumerordermanualpaymentfailedevent
      - name: durable_consumerorderpaymentsuccessevent
      - name: durable_consumerorderrefundedevent
      - name: durable_consumerorderscheduledpaymentfailedevent
      - name: durable_consumerprofileverifiedevent
      - name: durable_financedebtcollectionevent
      - name: durable_paymentcardtokenizedevent
      - name: durable_paymentwalletcreatedevent
      - name: durable_paymentwalletupdatedevent
      - name: durable_riskfrauddetectorresultevent
      - name: durable_riskselfiepersonverifyevent
      - name: pjnevents.durable_riskselfiepersonverifyevent2
      - name: durable_riskspendlimitupdateevent
      - name: volatile_marketingdealimpressionevent
      - name: volatile_consumeremailverifiedevent
      - name: volatile_consumerforgotpasswordevent
      - name: volatile_consumerorderactivatedevent
      - name: volatile_consumerordercancelledevent
      - name: volatile_consumerordermanualpaymentfailedevent
      - name: volatile_consumerorderpaymentsuccessevent
      - name: volatile_consumerorderpaymentupcomingevent
      - name: volatile_consumerorderrefundedevent
      - name: volatile_consumerorderscheduledpaymentfailedevent
      - name: volatile_consumerpaymentwalletupdatedevent
      - name: qldb_merchantbalance2024
      - name: qldb_contracts2024
      - name: rds_customer360_sandbox_account_emailaddress
      - name: rds_customer360_sandbox_account_emailconfirmation
      - name: durable_consumerpaymentwalletupdatedevent
      
      

      

      









      









